// The lucide half of the icon picker's grid.
//
// A curated list, not `Object.keys(lucide)`: the library ships well over a thousand
// glyphs, most of them arrows, chevrons and UI furniture that nobody would put on an
// agent instance. A 1500-cell grid is not a chooser, it is a haystack — so this is the
// subset that reads as an *identity* at 32 px, in the order a picker should show it
// (tools and machines first, then places and creatures, then plain marks).
//
// `instance.icon` still accepts any lucide name typed by hand; nothing here restricts
// what can be stored, it only decides what is offered. Every name below is verified
// against lucide-vue-next — an unknown one would silently render as Bot, which is
// exactly the kind of quiet wrongness a picker should not be able to produce.
export const GLYPH_CHOICES: string[] = [
  // work
  "bot",
  "terminal",
  "code",
  "code-2",
  "binary",
  "command",
  "cpu",
  "circuit-board",
  "server",
  "database",
  "network",
  "cloud",
  "globe",
  "plug",
  "radio",
  "radar",
  "gauge",
  "activity",
  "calculator",
  "pi",
  "infinity",
  "hash",
  // making things
  "wrench",
  "hammer",
  "pickaxe",
  "scissors",
  "pencil",
  "feather",
  "palette",
  "shapes",
  "blocks",
  "box",
  "boxes",
  "package",
  "puzzle",
  "factory",
  "recycle",
  // knowing things
  "brain",
  "lightbulb",
  "book",
  "book-open",
  "graduation-cap",
  "microscope",
  "telescope",
  "flask-conical",
  "test-tube",
  "atom",
  "orbit",
  "compass",
  "map",
  "search",
  "eye",
  // going places
  "rocket",
  "ship",
  "truck",
  "anchor",
  "tent",
  "briefcase",
  "coffee",
  "pizza",
  "egg",
  // signals
  "zap",
  "flame",
  "droplet",
  "waves",
  "wind",
  "tornado",
  "snowflake",
  "sun",
  "moon",
  "star",
  "sparkles",
  "gem",
  "diamond",
  "crown",
  "trophy",
  "heart",
  "shield",
  "key",
  "lock",
  "timer",
  "dice-5",
  "swords",
  "bug",
  "ghost",
  // living things
  "cat",
  "dog",
  "bird",
  "fish",
  "rabbit",
  "turtle",
  "squirrel",
  "worm",
  "leaf",
  "shrub",
  // talking
  "message-square",
  "mic",
  "headphones",
  "music",
  "camera",
  "gamepad-2",
  "file-text",
  "folder",
  "umbrella",
  "cog",
];
