//! dsh (DeepSeek Harness) runtime — the launcher's first-class agent.
//!
//! Moved verbatim from the former `dsh_runner`: the command shape is
//! `dsh --profile <p> [--patch <model.patch.yml>] "<task>"`, where the patch
//! overrides the `agent-default-model` plugin config for this instance's model.

use tokio::process::Command;

use super::{AgentRuntime, SpawnRequest};

/// The dsh runtime. Stateless — every input comes from the `SpawnRequest`.
pub struct DshRuntime;

impl AgentRuntime for DshRuntime {
    fn build_command(&self, req: &SpawnRequest) -> Result<Command, String> {
        let patch_path = write_model_patch(req)?;
        let mut cmd = Command::new("dsh");
        cmd.arg("--profile").arg(&req.instance.profile);
        if let Some(p) = &patch_path {
            cmd.arg("--patch").arg(p);
        }
        cmd.arg(req.task);
        Ok(cmd)
    }
}

/// Escape a scalar for a YAML double-quoted string.
fn yaml_quote(s: &str) -> String {
    let esc = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{esc}\"")
}

/// Write a `--patch` overlay overriding `agent-default-model` for this instance's
/// model, or `None` when the instance has no model set. deepseek-* ⇒ the official
/// DeepSeek provider route; other ids pass through on the same route (dsh does not
/// validate catalog membership — a dedicated provider route is future work).
fn write_model_patch(req: &SpawnRequest) -> Result<Option<String>, String> {
    let model = req.instance.model.trim();
    if model.is_empty() {
        return Ok(None);
    }
    let provider = "deepseek-official";
    let body = format!(
        "# Generated by dsh-launcher — maps this instance's model onto dsh.\n\
         - id: agent-default-model\n  \
           config:\n    \
             provider: {}\n    \
             model: {}\n",
        yaml_quote(provider),
        yaml_quote(model),
    );
    let path = req.instance_dir.join("model.patch.yml");
    std::fs::write(&path, body).map_err(|e| e.to_string())?;
    Ok(Some(path.to_string_lossy().to_string()))
}
