//! The six engine adapters — one file, one table.
//!
//! Every agent CLI differs only in *how the launch command is assembled*: the
//! binary name, the flag that makes the run non-interactive, and how provider /
//! model / task are injected. That is a handful of lines each, so a file per
//! engine hid the very thing it was meant to expose. Side by side the six
//! `build_command` bodies read as the matrix they are, and adding an engine is one
//! `impl` here plus rows in `model_test.rs` (which fails if a registered engine
//! has no rows).
//!
//! Invariants across all six:
//!
//! * **An empty provider or model omits its flag** — the engine then falls back to
//!   its own default instead of the launcher guessing one.
//! * **Provider strings pass through verbatim.** Namespaces are engine-specific
//!   (pi's `google` is not dsh's `deepseek-official`); the launcher does not
//!   normalize across engines.
//! * **No credentials here.** Each CLI reads its own env, injected from the
//!   instance `.env` by the executor.
//! * **`custom_bin` wins over the default binary** (see [`super::program`]).
//!
//! | engine | program | headless | provider | model |
//! |---|---|---|---|---|
//! | dsh | `dsh` | default (non-web profile) | `provider:` inside `model.patch.yml` | `--patch <file>` |
//! | pi | `pi` | `-p` | `--provider <p>` | `--model <m>` |
//! | omp | `omp` | `-p` | `--provider <p>` | `--model <m>` |
//! | claude | `claude` | `-p` | env only (`ANTHROPIC_*`), no flag | `--model <m>` |
//! | codex | `codex` | `exec` | `-c model_provider=<p>` | `-c model=<m>` |
//! | opencode | `opencode` | `run` | folded into `-m <p>/<m>` | `-m <p>/<m>` |

use tokio::process::Command;

use super::{program, AgentRuntime, SpawnRequest};
use crate::dsh_config;
use crate::instance_manager::Instance;

// ---------------------------------------------------------------- dsh

/// dsh (DeepSeek Harness) — the launcher's first-class agent and the only engine
/// with a web serve mode. `dsh --profile <p> [--patch <model.patch.yml>]
/// "<task>"`, where the patch overrides the `agent-default-model` plugin config
/// for this instance's model.
pub struct DshRuntime;

impl AgentRuntime for DshRuntime {
    fn id(&self) -> &'static str {
        "dsh"
    }

    fn build_command(&self, req: &SpawnRequest) -> Result<Command, String> {
        let patch_path = write_model_patch(req)?;
        let mut cmd = program(&req.instance.runtime.custom_bin, "dsh");
        cmd.arg("--profile").arg(&req.instance.profile);
        if let Some(p) = &patch_path {
            cmd.arg("--patch").arg(p);
        }
        if dsh_config::profile_is_web_capable(&req.instance.profile) {
            // Web profile: a long-running browser-UI server, not a one-shot task.
            // Pass no task; keep the launcher from hijacking the browser
            // (`--no-open` — the launcher opens the URL itself once it appears on
            // stdout), and let the OS pick a free port (`--port 0`) so multiple
            // web instances never collide on the default 3080.
            cmd.arg("--no-open").arg("--port").arg("0");
        } else {
            cmd.arg(req.task);
        }
        Ok(cmd)
    }

    fn is_serve(&self, inst: &Instance) -> bool {
        dsh_config::profile_is_web_capable(&inst.profile)
    }
}

/// Escape a scalar for a YAML double-quoted string.
fn yaml_quote(s: &str) -> String {
    let esc = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{esc}\"")
}

/// Write a `--patch` overlay overriding `agent-default-model` for this instance's
/// model, or `None` when the instance has no model set. The provider defaults to
/// the official DeepSeek route; a non-empty instance `provider` overrides it, so
/// a dsh instance can target another dsh provider route without touching code.
fn write_model_patch(req: &SpawnRequest) -> Result<Option<String>, String> {
    let model = req.instance.model.trim();
    if model.is_empty() {
        return Ok(None);
    }
    let provider = {
        let p = req.instance.provider.trim();
        if p.is_empty() {
            "deepseek-official"
        } else {
            p
        }
    };
    let body = format!(
        "# Generated by agentLauncher — maps this instance's model onto dsh.\n\
         - id: agent-default-model\n  \
           config:\n    \
             provider: {}\n    \
             model: {}\n",
        yaml_quote(provider),
        yaml_quote(model),
    );
    let path = req.instance_dir.join("model.patch.yml");
    std::fs::write(&path, body).map_err(|e| e.to_string())?;
    Ok(Some(path.to_string_lossy().to_string()))
}

// ------------------------------------------------------- pi family

/// The shared pi-family shape: `<bin> -p [--provider <p>] [--model <m>]
/// "<task>"`, where `-p/--print` is the non-interactive switch. `pi` and `omp`
/// (oh-my-pi) are the same CLI lineage and differ only in the binary name.
fn pi_family(bin: &'static str, req: &SpawnRequest) -> Command {
    let mut cmd = program(&req.instance.runtime.custom_bin, bin);
    cmd.arg("-p");
    let provider = req.instance.provider.trim();
    if !provider.is_empty() {
        cmd.arg("--provider").arg(provider);
    }
    let model = req.instance.model.trim();
    if !model.is_empty() {
        cmd.arg("--model").arg(model);
    }
    cmd.arg(req.task);
    cmd
}

/// pi (pi-coding-agent) — headless one-shot. Discovers AGENTS.md from the working
/// tree, so the executor's `cwd` placement is all the context it needs.
pub struct PiRuntime;

impl AgentRuntime for PiRuntime {
    fn id(&self) -> &'static str {
        "pi"
    }

    fn build_command(&self, req: &SpawnRequest) -> Result<Command, String> {
        Ok(pi_family("pi", req))
    }
}

/// omp (oh-my-pi) — headless one-shot, identical flag shape to `pi`.
pub struct OmpRuntime;

impl AgentRuntime for OmpRuntime {
    fn id(&self) -> &'static str {
        "omp"
    }

    fn build_command(&self, req: &SpawnRequest) -> Result<Command, String> {
        Ok(pi_family("omp", req))
    }
}

// ------------------------------------------------- claude / codex / opencode

/// claude (Claude Code) — headless one-shot via `-p/--print`. No provider flag
/// exists: provider, base URL, and key all come from `ANTHROPIC_*` in the instance
/// `.env`. Discovers AGENTS.md / CLAUDE.md from the working tree.
pub struct ClaudeRuntime;

impl AgentRuntime for ClaudeRuntime {
    fn id(&self) -> &'static str {
        "claude"
    }

    fn build_command(&self, req: &SpawnRequest) -> Result<Command, String> {
        let mut cmd = program(&req.instance.runtime.custom_bin, "claude");
        cmd.arg("-p");
        let model = req.instance.model.trim();
        if !model.is_empty() {
            cmd.arg("--model").arg(model);
        }
        cmd.arg(req.task);
        Ok(cmd)
    }
}

/// codex — headless one-shot via the `exec` subcommand. Model and provider ride in
/// as `-c` config overrides; codex parses each value as JSON with a string
/// fallback, so bare ids like `o3` / `gpt-5-codex` pass through unquoted. The
/// provider id must reference a `model_providers.<id>` table in the user's
/// `~/.codex/config.toml` — black-box passthrough, the launcher does not validate.
pub struct CodexRuntime;

impl AgentRuntime for CodexRuntime {
    fn id(&self) -> &'static str {
        "codex"
    }

    fn build_command(&self, req: &SpawnRequest) -> Result<Command, String> {
        let mut cmd = program(&req.instance.runtime.custom_bin, "codex");
        cmd.arg("exec");
        let model = req.instance.model.trim();
        if !model.is_empty() {
            cmd.arg("-c").arg(format!("model={model}"));
        }
        let provider = req.instance.provider.trim();
        if !provider.is_empty() {
            cmd.arg("-c").arg(format!("model_provider={provider}"));
        }
        cmd.arg(req.task);
        Ok(cmd)
    }
}

/// opencode — headless one-shot via the `run` subcommand. It takes a single
/// `provider/model` string, so the two halves fold into one `-m`; with no provider
/// we pass the bare model and let opencode resolve it against its own default.
/// (`opencode web` exists but is deliberately not wired — web stays dsh-only.)
pub struct OpencodeRuntime;

impl AgentRuntime for OpencodeRuntime {
    fn id(&self) -> &'static str {
        "opencode"
    }

    fn build_command(&self, req: &SpawnRequest) -> Result<Command, String> {
        let mut cmd = program(&req.instance.runtime.custom_bin, "opencode");
        cmd.arg("run");
        let provider = req.instance.provider.trim();
        let model = req.instance.model.trim();
        if !model.is_empty() {
            let m = if provider.is_empty() {
                model.to_string()
            } else {
                format!("{provider}/{model}")
            };
            cmd.arg("-m").arg(m);
        }
        cmd.arg(req.task);
        Ok(cmd)
    }
}
