use serde::Serialize;
use std::collections::HashMap;
use std::process::Stdio;
use std::sync::{Arc, Mutex};
use tauri::{AppHandle, Emitter, State};
use tokio::io::{AsyncReadExt, BufReader};
use tokio::process::Command;
use tokio::sync::mpsc;

use crate::instance_manager;

/// Maps a running instance id to a channel that kills its process.
type KillMap = Arc<Mutex<HashMap<String, mpsc::Sender<()>>>>;

/// Tracks a kill channel per running instance id.
#[derive(Default)]
pub struct RunnerState(pub KillMap);

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct LogEvent {
    instance_id: String,
    stream: String,
    chunk: String,
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct StatusEvent {
    instance_id: String,
    status: String,
    code: Option<i32>,
    message: Option<String>,
}

fn emit_status(app: &AppHandle, id: &str, status: &str, code: Option<i32>, message: Option<String>) {
    let _ = app.emit(
        "dsh-status",
        StatusEvent {
            instance_id: id.to_string(),
            status: status.to_string(),
            code,
            message,
        },
    );
}

fn emit_log(app: &AppHandle, id: &str, stream: &str, chunk: String) {
    let _ = app.emit(
        "dsh-log",
        LogEvent {
            instance_id: id.to_string(),
            stream: stream.to_string(),
            chunk,
        },
    );
}

/// Parse a minimal `.env` file into (key, value) pairs.
fn parse_env(path: &std::path::Path) -> Vec<(String, String)> {
    let mut out = vec![];
    if let Ok(text) = std::fs::read_to_string(path) {
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some((k, v)) = line.split_once('=') {
                let v = v.trim().trim_matches('"');
                out.push((k.trim().to_string(), v.to_string()));
            }
        }
    }
    out
}

/// Spawn a reader that streams a pipe to the frontend as chunks.
fn spawn_reader<R>(app: AppHandle, id: String, stream: &'static str, reader: R)
where
    R: tokio::io::AsyncRead + Unpin + Send + 'static,
{
    tokio::spawn(async move {
        let mut buf = [0u8; 4096];
        let mut r = BufReader::new(reader);
        loop {
            match r.read(&mut buf).await {
                Ok(0) => break,
                Ok(n) => {
                    let chunk = String::from_utf8_lossy(&buf[..n]).to_string();
                    emit_log(&app, &id, stream, chunk);
                }
                Err(_) => break,
            }
        }
    });
}

/// Escape a scalar for a YAML double-quoted string.
fn yaml_quote(s: &str) -> String {
    let esc = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{esc}\"")
}

/// Write a `--patch` overlay overriding `agent-default-model` for this instance's
/// model, or `None` when the instance has no model set. deepseek-* ⇒ the official
/// DeepSeek provider route; other ids pass through on the same route.
fn write_model_patch(id: &str, inst: &instance_manager::Instance) -> Result<Option<String>, String> {
    let model = inst.model.trim();
    if model.is_empty() {
        return Ok(None);
    }
    // The instance carries only a model id; route it on the official DeepSeek
    // provider. dsh does not validate catalog membership, so a non-deepseek id
    // still passes through (a dedicated pi-ai provider route is future work).
    let provider = "deepseek-official";
    let body = format!(
        "# Generated by dsh-launcher — maps this instance's model onto dsh.\n\
         - id: agent-default-model\n  \
           config:\n    \
             provider: {}\n    \
             model: {}\n",
        yaml_quote(provider),
        yaml_quote(model),
    );
    let path = instance_manager::instance_dir(id)?.join("model.patch.yml");
    std::fs::write(&path, body).map_err(|e| e.to_string())?;
    Ok(Some(path.to_string_lossy().to_string()))
}

pub async fn start(
    app: AppHandle,
    state: State<'_, RunnerState>,
    id: String,
    task: Option<String>,
) -> Result<(), String> {
    // Already running? stop the previous run first.
    let existing = state.0.lock().unwrap().get(&id).cloned();
    if let Some(tx) = existing {
        let _ = tx.send(()).await;
    }

    let inst = instance_manager::get_instance(&id)?;
    let workspace = instance_manager::workspace_dir(&id)?;
    let env_path = instance_manager::instance_dir(&id)?.join(".env");

    let task_text = task
        .filter(|t| !t.trim().is_empty())
        .or_else(|| {
            if inst.default_task.trim().is_empty() {
                None
            } else {
                Some(inst.default_task.clone())
            }
        })
        .unwrap_or_else(|| "介绍一下你自己，并列出当前 workspace 里的文件。".to_string());

    emit_status(&app, &id, "starting", None, None);

    // Map the instance's model choice onto a real dsh `--patch` overlay that
    // overrides the `agent-default-model` plugin config. deepseek-* models use the
    // official DeepSeek route; anything else is passed through on the same route
    // (dsh does not validate catalog membership).
    let patch_path = write_model_patch(&id, &inst)?;

    let mut cmd = Command::new("dsh");
    cmd.arg("--profile").arg(&inst.profile);
    if let Some(p) = &patch_path {
        cmd.arg("--patch").arg(p);
    }
    cmd.arg(&task_text)
        .current_dir(&workspace)
        .envs(parse_env(&env_path))
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());

    let mut child = cmd.spawn().map_err(|e| {
        let msg = format!("无法启动 dsh: {e}");
        emit_status(&app, &id, "error", None, Some(msg.clone()));
        msg
    })?;

    let stdout = child.stdout.take();
    let stderr = child.stderr.take();
    if let Some(out) = stdout {
        spawn_reader(app.clone(), id.clone(), "stdout", out);
    }
    if let Some(err) = stderr {
        spawn_reader(app.clone(), id.clone(), "stderr", err);
    }

    emit_status(&app, &id, "running", None, None);

    let (kill_tx, mut kill_rx) = mpsc::channel::<()>(1);
    state.0.lock().unwrap().insert(id.clone(), kill_tx);

    // Wait / kill supervisor.
    let app_wait = app.clone();
    let id_wait = id.clone();
    let map: KillMap = state.0.clone();
    tokio::spawn(async move {
        tokio::select! {
            status = child.wait() => {
                let code = status.ok().and_then(|s| s.code());
                emit_status(&app_wait, &id_wait, "exited", code, None);
            }
            _ = kill_rx.recv() => {
                let _ = child.kill().await;
                emit_status(&app_wait, &id_wait, "exited", None, Some("已手动结束".into()));
            }
        }
        map.lock().unwrap().remove(&id_wait);
    });

    Ok(())
}

pub async fn stop(state: State<'_, RunnerState>, id: String) -> Result<(), String> {
    let tx = state.0.lock().unwrap().remove(&id);
    if let Some(tx) = tx {
        let _ = tx.send(()).await;
        Ok(())
    } else {
        Err(format!("实例未在运行: {id}"))
    }
}
